#!/bin/bash

curl -L https://raw.githubusercontent.com/julsemaan/profile/master/profile/update > /usr/local/bin/jprofile_update
chmod +x /usr/local/bin/jprofile_update

curl -L https://raw.githubusercontent.com/julsemaan/profile/master/profile/user_install > /usr/local/bin/jprofile_install
chmod +x /usr/local/bin/jprofile_install

/usr/local/bin/jprofile_update

echo "+++++++++"
echo "+Done...+"
echo "+++++++++"
