#!/bin/bash

set -o nounset -o pipefail -o errexit

if ! which git; then
  echo "Needs git"
  exit 5
fi

d=$(mktemp -d)

function finish {
  rm -fr $d
}
trap finish EXIT

git clone https://github.com/julsemaan/profile $d

cp -a $d/profile/.bashrc_append /usr/local/etc/.bashrc_append
cp -a $d/profile/.inputrc /usr/local/etc/.inputrc
cp -a $d/profile/.tmux.conf /usr/local/etc/.tmux.conf
cp -a $d/profile/.vimrc /usr/local/etc/.vimrc
cp -a $d/profile/.gitignore /usr/local/etc/.gitignore

if ! [ -f /etc/cron.d/jprofile ]; then
  cp -a $d/profile/cron /etc/cron.d/jprofile
fi

if [ -f /etc/vimrc ]; then
	VIMRC="/etc/vimrc"
elif [ -f /etc/vim/vimrc ]; then
	VIMRC="/etc/vim/vimrc"
fi
if ! grep 'source /usr/local/etc/.vimrc' $VIMRC > /dev/null 2>&1 ; then
		echo "Installing the sourcing of vimrc in vimrc"
		echo 'source /usr/local/etc/.vimrc' >> $VIMRC
		echo "" >> $VIMRC
fi

git config --system core.excludesfile /usr/local/etc/.gitignore

homes=(/home/* /root)
for home in "${homes[@]}"; do 
  if [ "$home" != '/home/*' ]; then
    echo "Installing .tmux.conf in $home"
    cp /usr/local/etc/.tmux.conf $home/.tmux.conf
  
    echo "Installing .inputrc in $home"
    cp /usr/local/etc/.inputrc $home/.inputrc
 
    BASHRC="$home/.bashrc"
    if ! grep 'source /usr/local/etc/.bashrc_append' $BASHRC > /dev/null 2>&1 ; then
      echo "Installing the sourcing of bashrc_append in $BASHRC"
      echo 'source /usr/local/etc/.bashrc_append' >> $BASHRC
      echo "" >> $BASHRC
    fi
  fi
done

if ! [ -d /usr/local/etc/.vim/bundle/Vundle.vim ]; then
	git clone https://github.com/VundleVim/Vundle.vim.git /usr/local/etc/.vim/bundle/Vundle.vim
fi

if ! [ -d /usr/local/etc/ble.sh/out/ble.sh ]; then
  git clone --recursive https://github.com/akinomyoga/ble.sh.git
  make -C /usr/local/etc/ble.sh
fi

if ! [ -d /usr/local/etc/.fzf.bash ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git /usr/local/etc/fzf
  /usr/local/etc/fzf/install --all --no-update-rc
  mv $HOME/.fzf.bash /usr/local/etc/.fzf.bash
fi
