#!/bin/bash

curl -s -L https://raw.githubusercontent.com/julsemaan/profile/master/profile/install > /usr/local/bin/jprofile_install
chmod +x /usr/local/bin/jprofile_install

/usr/local/bin/jprofile_install

echo "+++++++++"
echo "+Done...+"
echo "+++++++++"
