#!/bin/bash

curl -L https://dl.dropboxusercontent.com/u/20280504/profile-files/vimrc > /usr/local/etc/.vimrc
curl -L https://dl.dropboxusercontent.com/u/20280504/profile-files/tmux.conf > /usr/local/etc/.tmux.conf
curl -L https://dl.dropboxusercontent.com/u/20280504/profile-files/bashrc_append > /usr/local/etc/.bashrc_append

/usr/local/bin/jprofile_install

