#!/bin/bash

if [ -f /etc/vimrc ]; then
	VIMRC="/etc/vimrc"
elif [ -f /etc/vim/vimrc ]; then
	VIMRC="/etc/vim/vimrc"
fi
if ! grep 'source /usr/local/etc/.vimrc' $VIMRC > /dev/null 2>&1 ; then
		echo "Installing the sourcing of vimrc in vimrc"
		echo 'source /usr/local/etc/.vimrc' >> $VIMRC
		echo "" >> $VIMRC
fi

if [ -f /etc/profile ]; then
	BASHRC="/etc/profile"
elif [ -f /etc/bash.bashrc ]; then
	BASHRC="/etc/bash.bashrc"
elif [ -f /etc/bashrc ]; then
	BASHRC="/etc/bashrc"
fi

if ! grep 'source /usr/local/etc/.bashrc_append' $BASHRC > /dev/null 2>&1 ; then
		echo "Installing the sourcing of bashrc_append in $BASHRC"
		echo 'source /usr/local/etc/.bashrc_append' >> $BASHRC
		echo "" >> $BASHRC
fi

homes=(/home/* /root)
for home in "${homes[@]}"; do 
  if [ "$home" != '/home/*' ]; then
    echo "Installing .tmux.conf in $home"
    cp /usr/local/etc/.tmux.conf $home/.tmux.conf
  
    BASHRC="$home/.bashrc"
    if ! grep 'source /usr/local/etc/.bashrc_append' $BASHRC > /dev/null 2>&1 ; then
      echo "Installing the sourcing of bashrc_append in $BASHRC"
      echo 'source /usr/local/etc/.bashrc_append' >> $BASHRC
      echo "" >> $BASHRC
    fi
  fi
done

if ! [ -d /usr/local/etc/.vim/bundle/Vundle.vim ]; then
	git clone https://github.com/VundleVim/Vundle.vim.git /usr/local/etc/.vim/bundle/Vundle.vim
fi
